# Generated by Django 5.1.14 on 2025-11-14 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='반려 동물 종류')),
            ],
            options={
                'verbose_name': '동물 종류',
                'verbose_name_plural': '동물 종류들',
                'db_table': 'animal_type',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='푸들, 코숏 등', max_length=100, verbose_name='품종명')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='models.animaltype', verbose_name='동물 종류')),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종들',
                'db_table': 'breed',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='models.breed', verbose_name='품종')),
            ],
            options={
                'verbose_name': '반려동물',
                'verbose_name_plural': '반려동물들',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='owner', help_text='owner, co-owner 등', max_length=50, verbose_name='역할')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pet', verbose_name='반려동물')),
            ],
            options={
                'verbose_name': '반려동물 소유권',
                'verbose_name_plural': '반려동물 소유권들',
                'db_table': 'pet_ownership',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='pets', through='models.PetOwnership', to=settings.AUTH_USER_MODEL, verbose_name='보호자들'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.UniqueConstraint(fields=('animal_type', 'name'), name='unique_breed_per_animal_type'),
        ),
        migrations.AddConstraint(
            model_name='petownership',
            constraint=models.UniqueConstraint(fields=('pet', 'owner'), name='unique_pet_owner'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['breed'], name='pet_breed_i_1d5a48_idx'),
        ),
    ]
